### PR TITLE
Add lecture 5 waiver and assignment directive for it to 106.

### PR DESCRIPTION
**Pull request by aerenchyma**
Has points also, same problem as the lecture 4 waiver, need retroactive change to threshold or to remove these directives.

If you'd like me to remove the directives let me know.

### CODE REVIEW

**Comment by presnick** [comment]
Looks like this one has merge conflicts. Can you resolve those?

**Comment by aerenchyma** [comment]
Resolving and will comment. Yes, this isn't necessary for tomorrow but would be good to have up soon so students can work on waiving Wednesday's lecture. (I put a note in this one that we strongly encourage them to be there, because it's iteration)

**Comment by aerenchyma** [comment]
Resolved.

**Comment by aerenchyma** [comment]
Uh oh, I broke it at the last second. Sorry. Fixing.

**Comment by aerenchyma** [comment]
Phew, OK.

**Pull request merged**
